repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argo-cd
    namespace: argocd
    chart: argo/argo-cd
    version: 5.46.7
    values:
      - argo-cd.yaml
  - name: argocd-image-updater
    namespace: argocd
    chart: argo/argocd-image-updater
    version: 0.9.1
    values:
      - argocd-image-updater.yaml
